### ISSUE TITLE
Using with Apollo

### ISSUE THREAD

**Issue by SachaG** [thereactivestack/meteor-react-router-ssr#101]
Are there any examples of using this package with Apollo? I know Apollo uses Redux under the hood, but I'm not sure how exactly to make them both work together.

**Comment by jasonnathan** [comment]
I recently posted a issue on https://github.com/apollostack/react-apollo/issues/296. I got it working by attaching the `preRender` hook to individual components based on the request:

````jsx
const BlogWithApollo = () => ( <ApolloProvider client={client}><Blog /></ApolloProvider>);

const preRender = (req) => {
    const segments = req.originalUrl.split('/').filter(p => p),
          controller = segments[0];

    switch(controller){
      case 'articles': return Promise.await(getDataFromTree(<BlogWithApollo />));
    }
}
````

It works, but I don't think I'm doing it properly. I suspect there is a better way to get route data in the `prerender` hook because some of my components don't have route data coming in to prepare the `graphql` query. I'm sort of stuck there myself. 

For `graphql` queries that don't rely on route data, it works.

**Comment by julian-rare** [comment]
also really stuck trying to get meteor-react-router-ssr to work with apollo, wen I merge the graphql query with the react component, meteor-react-router-ssr freaks out.

```
class Home extends React.Component {
    constructor(props) {
        super(props);
    }
    render() {
        console.log('render Home')
        return <div>Home</div>
    }
}

export default compose(
    graphql(allPosts)
)(Home);


```
I get an error in the console:

TypeError: serverOptions.fetchDataHook is not a function\n    at fetchComponentData (packages/reactrouter:react-router-ssr/lib/server.jsx:255:34)\n    at packages/reactrouter:react-router-ssr/lib/server.jsx:206:7\n    at [object Object]._.extend.withValue (packages\\meteor.js:1122:17)\n    at generateSSRData (packages/reactrouter:react-router-ssr/lib/server.jsx:181:29)\n    at sendSSRHtml (packages/reactrouter:react-router-ssr/lib/server.jsx:107:25)

**Comment by jasonnathan** [comment]
Hey @julian-rare I posted the steps to getting it working [here](https://www.jasonnathan.com/article/reactjs/how-to-ssr-with-apollostack-and-meteor-react-router-ssr). I also [forked this project](https://github.com/jasonnathan/meteor-react-router-ssr) and made [some changes](https://github.com/jasonnathan/meteor-react-router-ssr/commit/735bd21009b460463199ac1ff62f7cbaecd892a3)

**Comment by julian-rare** [comment]
Thank you @jasonnathan !

**Comment by julian-rare** [comment]
Sorry @jasonnathan, how do I install your version?
meteor add........ ?

**Comment by jasonnathan** [comment]
Why don't you post a comment in the blog or an issues in my fork?

This thread is closed

**Comment by julian-rare** [comment]
sorry @jasonnathan, the issue option is not available in your fork

**Comment by jasonnathan** [comment]
Sorqry @julian-rare, just enabled it. Open issues and i'll outline the steps

**Comment by julian-rare** [comment]
No worries, done https://github.com/jasonnathan/meteor-react-router-ssr/issues/1 and thank you for the quick response!

**Comment by AirBorne04** [comment]
> TypeError: serverOptions.fetchDataHook is not a function\n at fetchComponentData (packages/reactrouter:react-router-ssr/lib/server.jsx:255:34)\n at packages/reactrouter:react-router-ssr/lib/server.jsx:206:7\n at [object Object]._.extend.withValue (packages\meteor.js:1122:17)\n at generateSSRData (packages/reactrouter:react-router-ssr/lib/server.jsx:181:29)\n at sendSSRHtml (packages/reactrouter:react-router-ssr/lib/server.jsx:107:25)

I guess the problem here is that the fetchDataHook of the defined serverOptions is not a function and therefore the exception occurs. By correctly specifying a function or removing the property that error should go away.
