### ISSUE TITLE
WebApp is not defined

### ISSUE THREAD

**Issue by mikemurray** [thereactivestack/meteor-react-router-ssr#28]
I get this error while trying to use your package with `METEOR@1.3-modules-beta.2`.

```
I20160105-19:46:02.636(-8)? Exception in callback of async function: ReferenceError: WebApp is not defined
I20160105-19:46:02.636(-8)?     at packages/reactrouter:react-router-ssr/lib/server.jsx:51:5
I20160105-19:46:02.636(-8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160105-19:46:02.637(-8)?     at packages/meteor/dynamics_nodejs.js:123:1
I20160105-19:46:02.637(-8)?     at Object.ReactRouterSSR.Run (packages/reactrouter:react-router-ssr/lib/server.jsx:93:5)
...
```
Adding the following to the package.js seems to resolve the issue.
```js
api.use('webapp');
```

Since Meteor 1.3 is still in beta so this may change in the future, but just a heads up.

**Comment by eXon** [comment]
Thanks for reporting that. I will take a look and fix this. I'm also testing it with Meteor 1.3 :)
