### ISSUE TITLE
[3.0.1] Trouble with helmet

### ISSUE THREAD

**Issue by csillag** [thereactivestack/meteor-react-router-ssr#55]
OK, so now I am on 3.0.1.
I haven't added anything related to SEO, so no helmet.

When starting up the server, I am getting this in the browser:

```
[Error: Can't find npm module 'react-helmet/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
WARNING: npm peer requirements (for reactrouter:react-router-ssr) not installed:
 - react-helmet@3.x not installed.

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies
```

Does that mean that now I am required to install
1. the [nfl:react-helmet](https://atmospherejs.com/nfl/react-helmet) meteor package, or
2. the [react-helmet](https://www.npmjs.com/package/react-helmet) npm package,

or is there a problem with this package?

**Comment by csillag** [comment]
If I install the [nfl:react-helmet](https://atmospherejs.com/nfl/react-helmet) meteor package, I get this:

```
[Error: Can't find npm module 'react-helmet/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
(STDERR) WARNING: npm peer requirements (for reactrouter:react-router-ssr) not installed:
(STDERR)  - react-helmet@3.x not installed.
(STDERR)           
```

If I also install the [react-helmet](https://www.npmjs.com/package/react-helmet) npm package, then I get this:

```
[Error: Can't find npm module 'react-addons-transition-group/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
[Error: Can't find npm module 'react-addons-linked-state-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
[Error: Can't find npm module 'react-addons-create-fragment/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
[Error: Can't find npm module 'react-addons-update/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
[Error: Can't find npm module 'react-addons-perf/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
(STDERR) WARNING: npm peer requirements not installed:
(STDERR)  - react@15.0.2 installed, react@0.14.x needed
(STDERR)  - react-dom@15.0.2 installed, react-dom@0.14.x needed
(STDERR)  - react-addons-transition-group@0.14.x not installed.
(STDERR)  - react-addons-css-transition-group@15.0.2 installed, react-addons-css-transition-group@0.14.x needed
(STDERR)  - react-addons-linked-state-mixin@0.14.x not installed.
(STDERR)  - react-addons-create-fragment@0.14.x not installed.
(STDERR)  - react-addons-update@0.14.x not installed.
(STDERR)  - react-addons-pure-render-mixin@15.0.2 installed, react-addons-pure-render-mixin@0.14.x needed
(STDERR)  - react-addons-test-utils@15.0.2 installed, react-addons-test-utils@0.14.x needed
(STDERR)  - react-addons-perf@0.14.x not installed.
(STDERR)           
```

So, what is the required configuration here?

**Comment by csillag** [comment]
Any progress on this?

**Comment by clifforous** [comment]
I would guess that your project is still referencing the meteor react package.  Did you try "meteor remove react"?  You could also check your .meteor/packages and .meteor/versions for references to the meteor react package.   

Also, with the way the project is setup currently I believe you need to install react-helmet from NPM.

**Comment by csillag** [comment]
> I would guess that your project is still referencing the meteor react package. 

I have checked again, and that is definitely not the case.  The only react-related Meteor package I have installed is the [react-meteor-data](https://atmospherejs.com/meteor/react-meteor-data) package, which is needed by Meteor, but the rest of React comes from NPM packages.

**Comment by focused** [comment]
I did `meteor npm i -S react-router react-helmet` and still get this:
```
W20160506-00:32:08.454(3)? (STDERR)
W20160506-00:32:08.454(3)? (STDERR) /Users/focused/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160506-00:32:08.454(3)? (STDERR) 						throw(ex);
W20160506-00:32:08.454(3)? (STDERR) 						      ^
W20160506-00:32:08.480(3)? (STDERR) Error: Can't find npm module 'meteor/url'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160506-00:32:08.480(3)? (STDERR)     at Object.Npm.require (/Users/focused/Development/Meteor/simple-todos/.meteor/local/build/programs/server/boot.js:195:17)
W20160506-00:32:08.480(3)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20160506-00:32:08.480(3)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
W20160506-00:32:08.481(3)? (STDERR)     at meteorInstall.node_modules.meteor.reactrouter:react-router-ssr.lib.server.jsx (packages/reactrouter:react-router-ssr/lib/server.jsx:4:1)
W20160506-00:32:08.481(3)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160506-00:32:08.481(3)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160506-00:32:08.481(3)? (STDERR)     at meteorInstall.node_modules.meteor.reactrouter:react-router-ssr.lib.react-router-ssr.js (packages/reactrouter:react-router-ssr/lib/react-router-ssr.js:12:20)
W20160506-00:32:08.481(3)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160506-00:32:08.481(3)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160506-00:32:08.481(3)? (STDERR)     at /Users/focused/Development/Meteor/simple-todos/.meteor/local/build/programs/server/packages/reactrouter_react-router-ssr.js:677:15
```
But `meteor/url` is a core package, isn't it? What should I do to make it work, I do not want go with flow router... :(

**Comment by focused** [comment]
No more errors after `meteor add url` !!!

**Comment by eXon** [comment]
The url dependency has been fixed.

Helmet is no longer within react-router-ssr. There is an example on the readme on how to use it :)
