### ISSUE TITLE
ReferenceError: Tracker is not defined

### ISSUE THREAD

**Issue by SachaG** [thereactivestack/meteor-react-router-ssr#66]
Getting this error here: https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/ssr_data.js#L56

```
ReferenceError: Tracker is not defined
    at patchSubscribeData (packages/reactrouter:react-router-ssr/lib/ssr_data.js:56:27)
    at Object.ReactRouterSSR.Run (packages/reactrouter:react-router-ssr/lib/server.jsx:48:3)
    at meteorInstall.node_modules.meteor.nova:base-routes.lib.routes.jsx (packages/nova:base-routes/lib/routes.jsx:145:16)
     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
     at /Users/sacha/Dev/Telescope/.meteor/local/build/programs/server/packages/nova_base-routes.js:218:1
     at /Users/sacha/Dev/Telescope/.meteor/local/build/programs/server/packages/nova_base-routes.js:224:3
     at /Users/sacha/Dev/Telescope/.meteor/local/build/programs/server/boot.js:283:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/sacha/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
```

Maybe `Tracker` should be imported in `package.js`?

**Comment by eXon** [comment]
Yep thanks for your fix :)
